export type Language = 'ar' | 'tr' | 'en' | 'zh' | 'ja';
export const languages: { key: Language; label: string; native: string; rtl?: boolean }[] = [
  { key: 'ar', label: 'العربية', native: 'العربية', rtl: true },
  { key: 'tr', label: 'Türkçe', native: 'Türkçe' },
  { key: 'en', label: 'English', native: 'English' },
  { key: 'zh', label: '中文', native: '中文' },
  { key: 'ja', label: '日本語', native: '日本語' },
];

type Dictionary = Record<string, string>;
export const translations: Record<Language, Dictionary> = {
  ar: { brand: 'المتجر العالمي سوريا', country: 'سوريا', tagline: 'من بيتك إلى كل سوريا', hero: 'تسوق بثقة، وسعر واضح.', heroText: 'منتجات من متاجر سورية موثوقة، مع فصل سعر المنتج عن الشحن والجمارك قبل التأكيد.', clearCosts: 'الشحن والجمارك منفصلان وواضحان', search: 'ماذا تبحث اليوم؟', sections: 'الأقسام', all: 'الكل', featured: 'مختارات اليوم', stores: 'المتاجر', cart: 'السلة', account: 'حسابي', home: 'الرئيسية', smallStore: 'المتجر الصغير', largeStore: 'المتجر الكبير', admin: 'الإدارة', buyer: 'المشتري', browse: 'تصفح المنتجات', product: 'منتج', add: 'أضف', added: 'أضيف المنتج إلى السلة', emptyCart: 'السلة فارغة', checkout: 'تأكيد الطلب يدويًا', transparent: 'الفاتورة الشفافة', productsPrice: 'سعر المنتجات', shipping: 'الشحن التقديري', customs: 'الجمارك', customsPending: 'تُحسب حسب المنتج', totalBeforeCustoms: 'الإجمالي قبل الجمارك', smallRoom: 'غرفة المتجر الصغير', largeRoom: 'غرفة المتجر الكبير', smallDesc: 'إضافة منتجات، أكواد، كميات ومخزون.', largeDesc: 'آليات ومعدات وطلبات عرض حسب الطلب.', promotion: 'الإعلان المروّج', sevenDays: 'المدة ثابتة: 7 أيام', smallPrice: 'متجر صغير — 1 دولار', largePrice: 'متجر كبير — 10 دولارات', manual: 'الدفع اليدوي مفعّل', comingSoon: 'قريبًا', sendRequest: 'إرسال طلب للمراجعة', requestSent: 'أُرسل طلب الترويج إلى الإدارة', adminReview: 'مراجعة طلبات الترويج', accept: 'قبول', reject: 'رفض', requestAccepted: 'تم قبول طلب الترويج', requestRejected: 'تم رفض طلب الترويج', loginNote: 'تسجيل الدخول عبر الهاتف والرمز المؤقت', demoNote: 'هذه نسخة تجريبية. الربط الخلفي والدفع الحقيقي سيُضافان قبل الإنتاج.', orderPlaced: 'تم تسجيل طلبك تجريبيًا', backShopping: 'العودة للتسوق' },
  tr: { brand: 'Suriye Dünya Pazarı', country: 'Suriye', tagline: 'Evinizden tüm Suriye’ye', hero: 'Güvenle alışveriş, net fiyat.', heroText: 'Ürün, kargo ve gümrük bedelleri onaydan önce ayrı gösterilir.', clearCosts: 'Kargo ve gümrük ayrı ve şeffaf', search: 'Bugün ne arıyorsunuz?', sections: 'Kategoriler', all: 'Tümü', featured: 'Günün seçtikleri', stores: 'Mağazalar', cart: 'Sepet', account: 'Hesabım', home: 'Ana sayfa', smallStore: 'Küçük mağaza', largeStore: 'Büyük mağaza', admin: 'Yönetim', buyer: 'Alıcı', browse: 'Ürünlere göz at', product: 'ürün', add: 'Ekle', added: 'Ürün sepete eklendi', emptyCart: 'Sepet boş', checkout: 'Manuel siparişi onayla', transparent: 'Şeffaf fatura', productsPrice: 'Ürün fiyatı', shipping: 'Tahmini kargo', customs: 'Gümrük', customsPending: 'Ürüne göre hesaplanır', totalBeforeCustoms: 'Gümrük öncesi toplam', smallRoom: 'Küçük mağaza alanı', largeRoom: 'Büyük mağaza alanı', smallDesc: 'Ürün, kod, miktar ve stok ekleyin.', largeDesc: 'Makine, ekipman ve teklif talepleri.', promotion: 'Öne çıkan ilan', sevenDays: 'Süre sabit: 7 gün', smallPrice: 'Küçük mağaza — 1 dolar', largePrice: 'Büyük mağaza — 10 dolar', manual: 'Manuel ödeme aktif', comingSoon: 'Yakında', sendRequest: 'İnceleme için gönder', requestSent: 'Promosyon talebi yönetime gönderildi', adminReview: 'Promosyon taleplerini incele', accept: 'Kabul et', reject: 'Reddet', requestAccepted: 'Promosyon talebi kabul edildi', requestRejected: 'Promosyon talebi reddedildi', loginNote: 'Telefon ve tek kullanımlık kod ile giriş', demoNote: 'Bu bir demo sürümüdür. Gerçek bağlantılar üretimden önce eklenecek.', orderPlaced: 'Demo siparişiniz kaydedildi', backShopping: 'Alışverişe dön' },
  en: { brand: 'Almatjar Alalami Syria', country: 'Syria', tagline: 'From your home to all Syria', hero: 'Shop with confidence, clear prices.', heroText: 'Product, shipping and customs costs are shown separately before confirmation.', clearCosts: 'Shipping and customs are separate and clear', search: 'What are you looking for today?', sections: 'Categories', all: 'All', featured: 'Today’s picks', stores: 'Stores', cart: 'Cart', account: 'Account', home: 'Home', smallStore: 'Small store', largeStore: 'Large store', admin: 'Admin', buyer: 'Buyer', browse: 'Browse products', product: 'product', add: 'Add', added: 'Product added to cart', emptyCart: 'Your cart is empty', checkout: 'Confirm manual order', transparent: 'Transparent invoice', productsPrice: 'Products price', shipping: 'Estimated shipping', customs: 'Customs', customsPending: 'Calculated by product', totalBeforeCustoms: 'Total before customs', smallRoom: 'Small store room', largeRoom: 'Large store room', smallDesc: 'Add products, codes, quantities and stock.', largeDesc: 'Machinery, equipment and quote requests.', promotion: 'Promoted listing', sevenDays: 'Fixed duration: 7 days', smallPrice: 'Small store — 1 dollar', largePrice: 'Large store — 10 dollars', manual: 'Manual payment enabled', comingSoon: 'Coming soon', sendRequest: 'Send for review', requestSent: 'Promotion request sent to admin', adminReview: 'Review promotion requests', accept: 'Accept', reject: 'Reject', requestAccepted: 'Promotion request accepted', requestRejected: 'Promotion request rejected', loginNote: 'Sign in with phone and one-time code', demoNote: 'This is a demo. Real backend and payments will be added before production.', orderPlaced: 'Your demo order was recorded', backShopping: 'Back to shopping' },
  zh: { brand: '叙利亚环球商城', country: '叙利亚', tagline: '从家门口连接整个叙利亚', hero: '放心购物，价格透明。', heroText: '确认订单前，商品、运费和关税分别显示。', clearCosts: '运费和关税清晰分开', search: '今天想找什么？', sections: '分类', all: '全部', featured: '今日精选', stores: '商店', cart: '购物车', account: '我的账户', home: '首页', smallStore: '小型商店', largeStore: '大型商店', admin: '管理', buyer: '买家', browse: '浏览商品', product: '商品', add: '加入', added: '商品已加入购物车', emptyCart: '购物车为空', checkout: '确认手动订单', transparent: '透明账单', productsPrice: '商品价格', shipping: '预计运费', customs: '关税', customsPending: '按商品计算', totalBeforeCustoms: '关税前总计', smallRoom: '小型商店空间', largeRoom: '大型商店空间', smallDesc: '添加商品、代码、数量和库存。', largeDesc: '机械、设备和报价请求。', promotion: '推广广告', sevenDays: '固定时长：7天', smallPrice: '小型商店 — 1美元', largePrice: '大型商店 — 10美元', manual: '手动付款已启用', comingSoon: '即将推出', sendRequest: '提交审核', requestSent: '推广申请已发送给管理员', adminReview: '审核推广申请', accept: '接受', reject: '拒绝', requestAccepted: '推广申请已接受', requestRejected: '推广申请已拒绝', loginNote: '使用手机号和一次性验证码登录', demoNote: '这是演示版本。正式上线前将连接真实后端和支付。', orderPlaced: '演示订单已记录', backShopping: '继续购物' },
  ja: { brand: 'シリア・グローバルマーケット', country: 'シリア', tagline: '自宅からシリア全土へ', hero: '安心して、明確な価格で。', heroText: '確認前に商品・送料・関税を分けて表示します。', clearCosts: '送料と関税を明確に分離', search: '今日は何をお探しですか？', sections: 'カテゴリー', all: 'すべて', featured: '今日のおすすめ', stores: '店舗', cart: 'カート', account: 'アカウント', home: 'ホーム', smallStore: '小規模店舗', largeStore: '大規模店舗', admin: '管理', buyer: '購入者', browse: '商品を見る', product: '商品', add: '追加', added: 'カートに追加しました', emptyCart: 'カートは空です', checkout: '手動注文を確認', transparent: '明細が透明な請求書', productsPrice: '商品価格', shipping: '送料目安', customs: '関税', customsPending: '商品ごとに計算', totalBeforeCustoms: '関税前合計', smallRoom: '小規模店舗ルーム', largeRoom: '大規模店舗ルーム', smallDesc: '商品、コード、数量、在庫を追加。', largeDesc: '機械、設備、見積依頼。', promotion: 'プロモーション広告', sevenDays: '期間固定：7日間', smallPrice: '小規模店舗 — 1ドル', largePrice: '大規模店舗 — 10ドル', manual: '手動決済が有効', comingSoon: '近日公開', sendRequest: '審査に送信', requestSent: 'プロモーション申請を管理者へ送信しました', adminReview: 'プロモーション申請を審査', accept: '承認', reject: '却下', requestAccepted: '申請を承認しました', requestRejected: '申請を却下しました', loginNote: '電話番号とワンタイムコードでログイン', demoNote: 'これはデモ版です。正式公開前にバックエンドと決済を接続します。', orderPlaced: 'デモ注文を記録しました', backShopping: '買い物に戻る' },
};
export function isRTL(language: Language) { return language === 'ar'; }
